version: '3'
services:
  app:
    image: node:14.15.4-alpine
    container_name: mai_app
    environment:
      TZ: 'Asia/Tokyo'
    volumes:
      - ./:/usr/src
    working_dir:
      /usr/src/app
    command: sh -c 'npm run dev'
    tty: true
    ports:
      - '3000:3000'
    links:
      - db:db
    networks:
      - mai_network
  db:
    image: mysql:5.7
    container_name: mai_db
    env_file: ./db/.env
    environment:
      TZ: 'Asia/Tokyo'
      BIND-ADDRESS: 0.0.0.0
    tty: true
    ports:
      - '3306:3306'
    networks:
      mai_network:
        ipv4_address: ${MYSQL_HOST}
networks:
  mai_network:
    driver: bridge
    ipam:
      driver: default
      config:
       - subnet: $SUBNET
