version: '3'
services:
  app:
    image: node:14.15.4-alpine
    container_name: mai_app
    environment:
      MYSQL_SERVER: db
      TZ: 'Asia/Tokyo'
    volumes:
      - ./:/usr/src
    working_dir:
      /usr/src/app
    command: sh -c "npm run dev"
    tty: true
    ports:
      - "3000:3000"
    links:
      - db
      - db:database
  db:
    image: mysql:5.7
    container_name: mai_db
    env_file: ./db/mysql.env
    environment:
      TZ: 'Asia/Tokyo'
    tty: true
    ports:
      - "3306:3306"
  
