version: '3'
services:
  app:
    image: node:14.15.4-alpine
    container_name: mai_app
    environment:
      TZ: 'Asia/Tokyo'
    volumes:
      - ./:/usr/src
    working_dir:
      /usr/src/app
    command: sh -c 'npm run dev'
    tty: true
    ports:
      - '3000:3000'
